apiVersion: v1
kind: Service
metadata:
  name: siclient-{{ .Chart.Version | replace "." "-" }}
  labels:
    component: si
    role: client
    version: {{ .Chart.Version | replace "." "-" }}
spec:
  selector:
    component: si
    role: client
    version: {{ .Chart.Version | replace "." "-" }}
  ports:
  - name: http
    port: 8081
    protocol: TCP
