apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: siserver-{{ .Chart.Version | replace "." "-" }}
  labels:
    component: si
    role: server
    version: {{ .Chart.Version | replace "." "-" }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        component: si
        role: server
        version: {{ .Chart.Version | replace "." "-" }}
    spec:
      affinity:
        # Prefer to run server instances on different nodes
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - si
                - key: role
                  operator: In
                  values:
                  - server
                - key: version
                  operator: In
                  values:
                  - {{ .Chart.Version | replace "." "-" }}
              topologyKey: kubernetes.io/hostname
      containers:
      - name: siserver
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          successThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          timeoutSeconds: 2
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
